name: Test doc snippets

on:
  push:
    paths:
      - docs/components_page/**
  pull_request:
    paths:
      - docs/components_page/**

jobs:
  build-and-test:
    name: Build package and test snippets
    runs-on: 'ubuntu-latest'
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      firefox:
        image: selenium/node-chrome:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - uses: actions/checkout@v1
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install Dash
        run: python -m pip install -r requirements-dev.txt
      - name: Build dash-bootstrap-components
        run: npm run build
      - name: Install R dependencies from cran2deb4ubuntu
        run: |
          sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+
          sudo apt-get update
          sudo apt-get install r-recommended r-cran-dash
      - name: Install R package
        run: sudo R CMD INSTALL .
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.6.1'
      - name: Add Julia artifacts to repo for local install
        run: |
          inv edit-julia-dependencies
          git add -f deps/_components/dash_bootstrap_components.min.js src/*.jl src/jl/*.jl Project.toml
          git -c user.name="GitHub Actions" -c user.email="actions@github.com" commit -m "Add Julia build artifacts"
      - name: Install Julia dependencies
        run: julia -e 'using Pkg; Pkg.add([PackageSpec(name="Dash", version="1.0"), PackageSpec("HTTP")]); Pkg.add(path=".");'
      - name: Test Julia installation
        run: julia -e 'using Dash, DashBootstrapComponents, HTTP;'
      - name: Install nox
        run: python3.10 -m pip install -U nox
      - name: Test R and Julia docs snippets
        run: nox -s doctest
